name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Run WebdriverIO tests on Sauce Labs
          env:
            SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
            SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          run: npm run test:sauce
        - uses: actions/upload-artifact@v4
          if: ${{ always() }}
          with:
            name: allureReport
            path: ./allure-report 
