name: Visual Testing
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Run visual tests
          run: npm run test:visual 
        - name: List report files
          if: ${{ always() }}
          run: ls -la ./tmp/actual
        - name: Run visual reported
          if: ${{ always() }}
          run: npx npx wdio-visual-reporter --jsonOutput=./tmp/actual/output.json --reportFolder=./report--logLevel=debug
  
        - uses: actions/upload-artifact@v4
          if: ${{ always() }}
          with:
              name: visual-report
              path: ./report